apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: service-api
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: apicurio-registry