kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webhook-service-api
spec:
  to:
    kind: Service
    name: el-service-api
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None