resources:
- ../../base
- ../../../components/service-api/overlays/staging
- ../../../components/apicurio-registry/overlays/staging
- ../../../components/sso/overlays/staging
- allow-argocd.yaml



# - (additional resources that will only be applied in this environment)

# patches to resources in this environment
namespace: service-registry-staging

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

