kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: apicurio-registry
spec:
  to:
    kind: Service
    name: el-apicurio-registry
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None